# Docker compose file
version: '3.8'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "talking_text"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    command: python -m web_interface.app
    ports:
      - "5000:5000"
    volumes:
        - .:/talking_text
        - model_data:/root/.cache/torch/sentence_transformers/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

volumes:
    model_data: